name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 32510a98-fb5b-4e10-946f-f00a34490498
          SONAR_TOKEN: e62c84adbcfda79e46a9c096fbf892c15140994b
          args: >-
            -Dsonar.projectKey=neojarvis-testing_32510a98-fb5b-4e10-946f-f00a34490498
            -Dsonar.organization=neojarvis-testing
            -Dsonar.sources=aspnet-core-angular/,mvc-angularjs/src
            -Dsonar.verbose=true
